version: '3.4'
services:

  # a fully loaded development environment to test new code
  devbox: &devbox
    build:
      dockerfile: "./docker/devbox.dockerfile"
      context: "."
    image: "gbq_devbox"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./:/app

  # run all the tests and linting locally
  # - black & isort will format code to address issues
  test:
    <<: *devbox
    command: "docker/run_tests.sh --format-code"

  lock-requirements:
    <<: *devbox
    entrypoint: "/bin/bash"
    command: "docker/lock_requirements.sh"

  # generate and serve the project documentation locally
  mkdocs:
    image: "squidfunk/mkdocs-material:6.0.2"
    volumes:
      - ./:/docs
    ports:
      - "8000:8000"
