site_name: gbq Documentation
site_url: https://github.com/wayfair-incubator/gbq/docs/
repo_url: https://github.com/wayfair-incubator/gbq/
repo_name: wayfair-incubator/gbq
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Development Guide: development-guide.md
  - Changelog: changelog.md
theme: material
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "sphinx"
            heading_level: 3
            show_root_heading: True
            show_source: False
            show_root_full_path: False

extra:
  version:
    provider: mike
extra_css:
  - css/mkdocstrings.css
