site_name: gbq Documentation
repo_url: https://github.com/wayfair-incubator/gbq/
repo_name: wayfair-incubator/gbq
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Development Guide: development-guide.md
  - Changelog: changelog.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            heading_level: 3
            show_root_heading: True
            show_source: False
            show_root_full_path: False
  - mkdocstrings_patch_type_aliases

extra_css:
  - css/version-select.css
  - css/mkdocstrings.css
extra_javascript:
  - js/version-select.js
