#!/usr/bin/env bash

uv pip uninstall --system -r <(uv pip freeze --system)
uv pip install --system -r requirements.txt
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" > requirements.lock
uv pip freeze --system >> requirements.lock

echo "Rebuild containers to verify there are no conflicts."
