name: Version Bump merged

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged &&
        startsWith(github.head_ref, 'bump_version_to_') &&
        startsWith(github.event.pull_request.title, 'Bump version') &&
        contains(github.event.pull_request.title, ' → ')
    environment: Create Release
    steps:
      - name: Get new version
        id: get-new-version
        run: |
          NEW_VERSION=$(echo ${{ github.head_ref }} | cut -d _ -f4 )
          echo "::set-output name=version::$NEW_VERSION"
      - name: Is prerelease?
        id: is-prerelease
        run: |
          IS_PRERELEASE=$([[ "${{ steps.get-new-version.outputs.version }}" == *-[a-z]* ]] && echo true || echo false)
          echo "::set-output name=result::$IS_PRERELEASE"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: v${{ steps.get-new-version.outputs.version }}
          release_name: v${{ steps.get-new-version.outputs.version }} Release
          prerelease: ${{ steps.is-prerelease.outputs.result }}